apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: {{ .Values.wordpress.replicas}}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image : {{ .Values.wordpress.image}}
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql:80"
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.mysql.rootPassword | quote }}
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.mysql.database | quote }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
  - port: 80
    targetPort: 80